### ISSUE TITLE
Height Limit?

### ISSUE THREAD

**Issue by seangiles** [microweber/screen#46]
Hi. More of a question than an issue. Is there a height limit on the capture as I am getting a large black block at the bottom of the image (it is 34995px high). Some of the content that I am trying to screen shot is missing and there is just black.

Thanks.

**Comment by seangiles** [comment]
Has anyone else experienced this? 

Thanks.

**Comment by MASNathan** [comment]
Hello @seangiles ,

Are you using the latest version?

That happens when there is no backgound color set to the page, we (`Rocket Scientists`) call it ´void´.
Given that height, the webpage should be displayed, unless for some reason (on the website side), the page hides some stuff with the `overflow: scroll` css property or some other voodoo.

It could also be a bug :smiley: 

If you provide the url maybe I can look into it.
